# Generated by Django 2.1.1 on 2018-09-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_manager', '0002_book_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('number', models.IntegerField(max_length=50, verbose_name='读者号')),
                ('tel', models.IntegerField(max_length=50, verbose_name='联系方式')),
            ],
            options={
                'verbose_name': '读者信息',
                'verbose_name_plural': '读者信息',
                'db_table': 'Reader',
            },
        ),
    ]
