# Generated by Django 2.1.1 on 2018-09-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_manager', '0004_auto_20180907_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reader',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.RemoveField(
            model_name='reader',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='tel',
        ),
        migrations.AddField(
            model_name='reader',
            name='password',
            field=models.CharField(default=1, max_length=100, verbose_name='密码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reader',
            name='name',
            field=models.CharField(max_length=100, verbose_name='用户名'),
        ),
    ]
