# Generated by Django 2.1.1 on 2018-09-10 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_manager', '0005_auto_20180907_1704'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reader',
            new_name='User',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
