# Generated by Django 2.1.1 on 2018-09-10 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_manager', '0006_auto_20180910_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
