# Generated by Django 2.1.1 on 2018-09-13 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_manager', '0008_auto_20180911_2037'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.AlterModelTable(
            name='book',
            table='BOOK',
        ),
    ]
